# Generated by Django 5.1.3 on 2024-11-11 18:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('age', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(800)], verbose_name='Pet age')),
                ('description', models.TextField()),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('gender', models.CharField(choices=[('female', 'Female'), ('male', 'Male'), ('Other', 'Other'), ('not_mentioned', 'Prefer Not to Say')], max_length=20)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('medical_history', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='PetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('breed', models.CharField(max_length=100, null=True)),
                ('species', models.CharField(max_length=100)),
                ('habitat', models.CharField(blank=True, max_length=100, null=True)),
                ('temperament', models.TextField(blank=True, null=True)),
                ('excercise_needs', models.TextField(blank=True, null=True)),
                ('idea_environment', models.TextField(blank=True, null=True)),
                ('care_instructions', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PetBelonging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('dimensions', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.pet')),
            ],
        ),
        migrations.CreateModel(
            name='PetBelongingsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_link', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.petbelonging')),
            ],
        ),
        migrations.CreateModel(
            name='PetInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('routine', models.TextField(blank=True, null=True)),
                ('eating_habits', models.TextField(blank=True, null=True)),
                ('play_time', models.CharField(blank=True, max_length=100, null=True)),
                ('wake_up_time', models.CharField(blank=True, max_length=100, null=True)),
                ('sleep_up_time', models.CharField(blank=True, max_length=100, null=True)),
                ('behavior', models.CharField(blank=True, max_length=100, null=True)),
                ('special_needs', models.TextField(blank=True, null=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.pet')),
            ],
        ),
        migrations.CreateModel(
            name='PetMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_link', models.TextField()),
                ('resource_type', models.CharField(choices=[('audio', 'Voice'), ('image', 'Picture'), ('video', 'Video')], max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('caption', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.pet')),
            ],
        ),
    ]
